import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next.js; tools/ is build tooling, not app code.
    ignores: [".next/**", "node_modules/**", "tools/**", "next-env.d.ts"],
  },
  {
    rules: {
      // The ported markup keeps plain <img>; images are served unoptimised so
      // next/image would add no benefit and needs intrinsic sizes we don't have.
      "@next/next/no-img-element": "off",
      // Body copy is ported verbatim from the source template. Apostrophes in
      // JSX text render correctly; escaping them would only churn the content.
      "react/no-unescaped-entities": "off",
    },
  },
];

export default config;
